package day8_test

import (
	"fmt"
	"strings"

	"github.com/okulik/AoC2024/pkg/day8"
)

var testInput string = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`

func ExampleAntennaFinder_CountUniqueAntinodes() {
	af := day8.NewAntennaFinder(strings.NewReader(testInput))
	fmt.Println(af.CountUniqueAntinodes())
	// Output: 14
}
